### PR TITLE
Updated Documentation

### PR DESCRIPTION
**Pull request by RaamAnalyst**
Added Aim / About, Installation (npm i), and Contributing Guidelines.

### CODE REVIEW

**Comment by mayankmohak** [comment]
Tq for such a content full documentation.
Please remove the section `Learn More` as it is not that much needed in the context of this project.

**Comment by RaamAnalyst** [comment]
Removed the section Learn More.

**Comment by mayankmohak** [comment]
tq for your effort.
I would like to invite you to work on this project adding more sorting algorithms.

**Comment by RaamAnalyst** [comment]
Sure. I will do.

**Pull request merged**
